### ISSUE TITLE
"mouseenter" event does not fire on <button> and it's descendants in Firefox

### ISSUE THREAD

**Issue by ickata** [mootools/mootools-core#2662]
This is a bug in Firefox's core: https://bugzilla.mozilla.org/show_bug.cgi?id=1084196 && https://bugzilla.mozilla.org/show_bug.cgi?id=843003

However, I'm not sure that they're going to fix this soon. But as the idea of the JS frameworks/libs is to standardize browsers and to fix cross-browser issues, I think we need to patch this in MooTools.

I have already patched this locally. Let me know if you give me green light to make a pull request.

**Comment by ibolmo** [comment]
We've decided that this is too much burden for MooTools, and although you provided a patch, the patch is a fragile due to the calculations. It could be easily fix when Mozilla/Firefox actually want to fix the Internet.

**Comment by kentaromiura** [comment]
So, just to be a bit more argumentative, we think this is definitely an issue, as buttons are used for UX instead of using anchors.
I can see some problems with your PR, namely:
- You used Browser sniffing, which we have de-facto deprecated, so instead of doing Browser.name == 'firefox' you should create a bug detection instead, I think a viable solution would be to try to create a button with anything in it, and to use a synthetic event to see if it propagates, as I understand from the bugzilla page this bug isn't just on hover but for any kind of mouse events.
- the limit thing is weird, you can do a getParent('button') and check if it returns a button instance
- you also probably don't need to store anything but just to pass the event to the button children, or even better to the `this` of the addEvent, if anything the actual callback should be stored on the `this` element as to use the same hack with removeEvent later if necessary

**Comment by ickata** [comment]
1. Agree with the bug detection approach, but this will be more heavy & will slow-down the framework bootstrap.

2. Limit thing is not weird at all - consider having a DOM-heavy environment with thousands of nested elements - in case `getParent` does not match anything it will traverse up to `document`, which will be very slow.

3. I can think in that direction, however, the guys decided that this won't be fixed, so it is not worth spending any more time on this. I have a local patch of this issue on my system - well, it would be better if the framework was dealing with this issue instead of me ugly patching it...
