### ISSUE TITLE
The bind 'polyfill' is incomplete

### ISSUE THREAD

**Issue by mako-taco** [mootools/mootools-core#2707]
Deleting `Function.prototype.bind` and replacing it with a non-working polyfill causes conflicts with other libraries for no good reason. The `bind` polyfill provided by mootools does not account for appended arguments that are bound to a function.

You can see an [example on jsfiddle](https://jsfiddle.net/z1f12s6p/).

**Comment by DimitarChristoff** [comment]
technically, it's not a polyfill as MooTools' `bind` pre-dates the standardisation of `Fn.proto.bind` 

because of that, it differs. it's now a `protected` method but for compat's sake, it can also remain broken :)

please see https://github.com/mootools/mootools-core/issues/2473 - just stop using the compatibility build version of mootools.

**Comment by arian** [comment]
As MooTools added `Function.prototype.bind` in like 2006, before it existed in ES5. Unfortunately that version is incompatible with ES5 .bind.

However we fixed that in version 1.3 a few years ago. The old behavior is only there to provide compatibility with old MooTools scripts.

In the default download on mootools.net, this compat layer is disabled by default.

So if you use the right (default) build, it will work fine, as it should.
