### ISSUE TITLE
Mouseleave on select

### ISSUE THREAD

**Issue by 22c-proxima** [mootools/mootools-core#2710]
Good day, dear mootools developers

I have using your great framework for years (just decades), and very enjoyed it.

I found one feature that looks like bug: when I attached mouseout event on container, that contains "select" element, and someone open this select - mouseleave is fired (in IE11, Opera 28, Chrome 41). Only Firefox handles mouseleave the way I suspect (not fired, because options is children of select, so - here no leaving).

__jsFiddle:__ https://jsfiddle.net/2t8ctdoe/

Code of page that illustrates this issue:

```
<html><head>
<title>Mootools event mouseleave error</title>
<style>

div#targetDiv {
	height: 100px;
	width: 500px;
	padding: 20px;

	border-color: black;
	border-style: solid;
	border-width: 1px;

	background-color: lightgray;
}

div.hovered {
	background-color: lightblue !important;
}

</style>
<script type="text/javascript" src="mootools-core-1.5.1.js"></script>
<script type="text/javascript">

window.addEvent('domready', function() {
	$('targetDiv').addEvents({
		mouseenter: function() {
			this.addClass('hovered');
		},
		mouseleave: function() {
			this.removeClass('hovered');
		}
	});
});

</script>
</head><body>

<div id="targetDiv">
    <select>
        <option>1</option>
        <option>2</option>
        <option>3</option>
        <option>4</option>
        <option>5</option>
        <option>6</option>
        <option>7</option>
        <option>8</option>
        <option>9</option>
        <option>10</option>
        <option>11</option>
        <option>12</option>
        <option>13</option>
        <option>14</option>
        <option>15</option>
    </select>
</div>

</body></html>
```

**Comment by SergioCrisostomo** [comment]
I would say this is difficult to fix since Browsers implementation of the `select` "window" is unreliable. Other frameworks [have been pointed out to have the same](http://stackoverflow.com/questions/6212309/problem-with-jquery-mouseleave-firing-when-container-has-select-box) "bug".

I don't see a way to fix this in a consistent way. Even using `event.fromElement` which is `null` for that `mouseleave` event would be a partial solution (https://jsfiddle.net/2t8ctdoe/1/) since you can get away from the element unnoticed if exiting by the select options "window" when opened.

**Comment by 22c-proxima** [comment]
Thank you, Sergio. I'll try that solution. Good luck to you
