### ISSUE TITLE
mootools-core 1.5.1 uglify.js

### ISSUE THREAD

**Issue by Shoplifter** [mootools/mootools-core#2717]
when i minify mootools-core 1.5.1 using uglify.js i get this error message:
    
    uglifyjs js/mootools-core-1.5.1.js --compress --mangle -o js/mootools-core-1.5.1.min.js

    util.error: Use console.error instead
    WARN: Side effects in initialization of unused variable instanceOf [js/mootools-core-1.5.1.js:51,4]
    util.error: Use console.error instead
    WARN: Dropping unused function borderBox [js/mootools-core-1.5.1.js:4666,9]

dont know what that means, any idea?

**Comment by SergioCrisostomo** [comment]
>Side effects in initialization of unused variable instanceOf

This is because we use `var instanceOf = this.instanceOf = function(item, object){` [in Core.js](https://github.com/mootools/mootools-core/blob/1.5.1/dist/mootools-core.js#L47) and Uglify probably reacts to the first assignment of this "double assign", since `this.instanceOf` is not defined before that line. 

Using

```
var instanceOf;
instanceOf = this.instanceOf = function(item, object){
```

will not generate the warning, which made me reach the conclusion above.

>Dropping unused function borderBox

`borderBox` is a private function [used in Element.Dimentions in the compat layer](https://github.com/mootools/mootools-core/blob/dced8db93a60c1adf065defded170621100302c7/Source/Element/Element.Dimensions.js#L169). We could add a comment block around this code so it would not be in the no-compat build.

___

Having this said, I think its safe to ignore those warnings.

**Comment by Shoplifter** [comment]
thank you for digging into this and providing comprehensive answer.
