### ISSUE TITLE
Object.values less tolerant in 1.5.3 dev vs 1.5.1

### ISSUE THREAD

**Issue by si13b** [mootools/mootools-core#2746]
Object values in 1.5.1:
```
Object.values(null)
=> []
```

Object values in 1.5.3 dev:
```
Object.values(null)
=> Uncaught TypeError: Cannot convert undefined or null to object(…)
```

**Comment by arian** [comment]
That's because it uses `Object.keys` now, which internally uses [`ToObject(o)`](http://www.ecma-international.org/ecma-262/6.0/index.html#sec-toobject) (for newer browsers at least), which throws for `null` and `undefined`. 

For MooTools, the behavior of other types of values is not documented, so we don't guarantee the result of `Object.values(null)`.

Looking at the [ES2016 proposal](https://github.com/ljharb/proposal-object-values-entries/blob/master/spec.md) for Object.values, it will use `ToObject(o)` as well, so is more or less consisted with MooTools 1.5.2 Object.values

**Comment by si13b** [comment]
That makes sense and it's probably the preferred behaviour, especially if it's consistent with the (potentially) native implementation. I'm not sure if it's worth flagging this somewhere in the docs or not so users know there's a potentially breaking change when upgrading from 1.5.1?

Feel free to close this one.
