### ISSUE TITLE
node modules error

### ISSUE THREAD

**Issue by LeviAckerman1234** [mootools/mootools-core#2833]
hi because of mootools i am getting 2 moderate severity vulnerabilities npm audit fix wont do anything any fix for this need this fixed asap

**Comment by orf** [comment]
Honest question, because I’ve always wanted to know. What makes people like yourself open such completely vague issues like this?

I would assume it would be totally obvious that you should include at the very least a link to the security vulnerabilities you are referencing, or _some_ kind of screenshot or output from NPM audit. Or just _something_. All this is issue is shouting “it doesn’t work” into the void that is a clearly unmaintained repository. 

So out of genuine interest, why did you decide to open an issue like this with absolutely no information anyone can use to actually help you @LeviAckerman1234?

**Comment by orf** [comment]
You've done the same thing in a bunch of other places:

- https://github.com/RealYuri001/basic-global-ban/issues/6
- https://github.com/xaxim/banban/issues/5
- https://github.com/lkaesberg/EmailVerify/issues/13
- https://github.com/KeyAuth/KeyAuth-Discord-Bot/issues/12
- https://github.com/cryptographic1337/Vouch-Plus/issues/1

I'm being serious, I'd really like to understand your thought processes behind creating these issues. Do you make a conscious choice to not include any details in any of these issues, or does it just not cross your mind? If it's the latter then why?

**Comment by SergioCrisostomo** [comment]
Please be more specific and explain how to reproduce your errors.
